#!/usr/bin/env bash

gsettings set org.gnome.desktop.background color-shading-type 'solid'
gsettings set org.gnome.desktop.background primary-color '#72729f9fcfcf'
gsettings set org.gnome.desktop.background show-desktop-icons true
gsettings set org.gnome.desktop.background draw-background true
gsettings set org.gnome.desktop.background picture-options 'none'

gsettings set org.gnome.desktop.interface clock-format '24h'
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-seconds true

gsettings set com.canonical.indicator.datetime.show-date true
gsettings set com.canonical.indicator.datetime.show-year true
gsettings set com.canonical.indicator.datetime.show-day true
gsettings set com.canonical.indicator.datetime.show-seconds true
gsettings set com.canonical.indicator.datetime.show-week-numbers true

gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar 'toggle-maximize'

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Alt>exclam']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Alt>quotedbl']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Alt>section']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Alt>dollar']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Alt>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Alt>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Alt>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Alt>4']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['F10']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['F11']"

gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Alt>less'
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver '<Super>l'
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up '<Super>Up'
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down '<Super>Down'
gsettings set org.gnome.settings-daemon.plugins.media-keys next '<Super>Rigth'
gsettings set org.gnome.settings-daemon.plugins.media-keys previous '<Super>Left'

gsettings set org.gnome.desktop.default-applications.terminal exec 'gnome-terminal'
gsettings set org.gnome.desktop.default-applications.terminal exec-arg '-x'

gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power idle-dim false

gsettings set com.ubuntu.update-notifier no-show-notifications true

gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 1800
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 1800
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.desktop.session idle-delay uint32 0

gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

RAW_GNOME_TERMINAL_PROFILE_ID=$(gsettings get org.gnome.Terminal.ProfilesList default)
GNOME_TERMINAL_PROFILE_ID=${RAW_GNOME_TERMINAL_PROFILE_ID:1:-1}

dconf write /org/gnome/terminal/legacy/profiles:/:${GNOME_TERMINAL_PROFILE_ID}/scrollback-unlimited true
dconf write /org/gnome/terminal/legacy/profiles:/:${GNOME_TERMINAL_PROFILE_ID}/scrollbar-policy never
dconf write /org/gnome/terminal/legacy/profiles:/:${GNOME_TERMINAL_PROFILE_ID}/default-size-columns 120
dconf write /org/gnome/terminal/legacy/profiles:/:${GNOME_TERMINAL_PROFILE_ID}/default-size-rows 30
